### ISSUE TITLE
Issues with Playfab/Steam cloud save progress determining

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#1]
**Describe the bug**
For both Playfab and Steam, there is no U2-specific HZE/Total Radon/Total Portal check, which makes it difficult for users to determine which save is newer when prompted.

In addition, it is reported that the "is Playfab save newer than local save?" check always fails if the Playfab save is on z1 of U2, with this line of code being the potential suspect due to `zonesCleared.value` being 0 on zone 1.
```js
var playFabTotalZones = (playFabSave.stats.zonesCleared.value) ? (playFabSave.stats.zonesCleared.value + playFabSave.stats.zonesCleared.valueTotal) : 0; 
```

**Comment by Trimps** [comment]
Fixed in 5.7.2!

**Comment by jasperfirecai2** [comment]
for me, playfab saves still show u1 stats when loading a u2 save
